Mwpfe 35 contacts form component
MagicJourney-Labs/magicjourney-labs-app pull request #37
Opened 2023-09-08 08:53 UTC by Martynas-J

I have added a contact form that sends data to gmail

2023-09-08 19:44 UTC, mbitc commented on .vscode/settings.json
> +  "[json]": {
why not Prettier?

2023-09-08 19:47 UTC, mbitc requested changes
Easy job, few place

2023-09-08 19:47 UTC, mbitc commented on src/components/ui/FormItem.jsx
> +        </button>
We have button component...

2023-09-13 04:58 UTC, Martynas-J commented on src/components/ui/FormItem.jsx
> +        </button>
I fixed it

2023-09-13 10:40 UTC, mbitc approved these changes

2023-09-13 10:40 UTC, merged